version: '3.1'
services:
  stats-server:
    build: stats-server
    image: olga-explorewithme-stats-image
    container_name: olga-explorewithme-stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit;MODE=PostgreSQL
        - SPRING_DATASOURCE_USERNAME=user
        - SPRING_DATASOURCE_PASSWORD=userpassword
        - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: olga-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword

  ewm-service:
    build: ewm-service
    image: olga-explorewithme-ewm-image
    container_name: olga-explorewithme-ewm-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit;MODE=PostgreSQL
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14-alpine
    container_name: olga-ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword
